name = "a11-dapp"
main = "worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[vars]
ENVIRONMENT = "production"

[env.dev]
vars = { ENVIRONMENT = "development" }